### ISSUE TITLE
PROJECT_PATH problem

### ISSUE THREAD

**Issue by beregond** [PeRDy/django-status#2]
So, I have an issue with django-status after upgrading from 1.0.5 to 1.1.2, since `PROJECT_PATH` is now required:
- Can't say why for `PROJECT_PATH` is for? Docs don't say if this is main app, or django project, or what? I had to dig through code to see this is for repository. My repo is a level higher, so even if I needed that, I'd make a mistake.
- I don't use repo check, or db check, only `ping` feature - it's hard to disable default checks and docs aren't helpful :/
- Because I don't use repo check, I don't really need `PROJECT_PATH` set, but since settings are eagerly checking if this setting is present I must set `PROJECT_PATH = ''`

Anyway thanks for this nice app :)

**Comment by perdy** [comment]
Hi @beregond.

Yes, you're right, I completely forgot to include a reference of this new setting in the readme. And, again, you're right that this might be optional, if you don't want to check your code status this setting shouldn't be necessary. I'll fix asap. 

Also, about disable default checks, I can handle this too, I'll try to do this for next version.

Thanks for your feedback.
